name: Terraform Confluent Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment to destroy (dev, stage, prod)"
        required: true
        default: "dev"

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}

    env:
      TF_VAR_confluent_cloud_api_key: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      TF_VAR_confluent_cloud_api_secret: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
      TF_VAR_organization_id: ${{ secrets.CONFLUENT_ORG_ID }}
      TF_VAR_by_env: ${{ github.event.inputs.environment || 'dev' }}
      TF_VAR_region: eastus2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4

      - name: Terraform Init
        working-directory: ./confluent-env
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./confluent-env
        env:
          TF_VAR_confluent_cloud_api_key: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
          TF_VAR_confluent_cloud_api_secret: ${{ secrets.CONFLUENT_CLOUD_API_SECRET }}
        run: terraform destroy -auto-approve -var-file="envs/${{ env.TF_VAR_by_env }}.tfvars"
